/* LR/LALR(1) parser for NDLang's *expression* subgrammar, generated by Bison.
 *
 * This exists purely for the recursive-descent vs. LR comparison in
 * docs/parsing-comparison.md. It evaluates expressions over floats and
 * fixed-size vectors, e.g.   [1, 2, 3] * 2 + [4, 5, 6]
 *
 * Precedence is spelled out with %left / %right (contrast with the
 * recursive-descent parser, where it is implied by the call structure).
 */
%{
#include <cstdio>
#include <cstdlib>
#include <vector>

struct V {
  bool vec = false;
  std::vector<double> x;
};

int yylex(void);
void yyerror(const char *msg);
static V *result = nullptr;
static bool failed = false;

static V *scalar(double d) {
  V *v = new V;
  v->x.push_back(d);
  return v;
}

static V *binop(char op, V *a, V *b) {
  if (a->vec && b->vec && a->x.size() != b->x.size()) {
    yyerror("vector dimension mismatch");
    delete b;
    return a;
  }
  if (a->vec && b->vec == false && (op == '+' || op == '-')) {
    yyerror("cannot add/subtract a scalar and a vector");
    delete b;
    return a;
  }
  V *r = new V;
  r->vec = a->vec || b->vec;
  size_t n = a->vec ? a->x.size() : b->x.size();
  for (size_t i = 0; i < n; ++i) {
    double l = a->vec ? a->x[i] : a->x[0];
    double rr = b->vec ? b->x[i] : b->x[0];
    switch (op) {
    case '+': r->x.push_back(l + rr); break;
    case '-': r->x.push_back(l - rr); break;
    case '*': r->x.push_back(l * rr); break;
    default: r->x.push_back(l / rr); break;
    }
  }
  delete a;
  delete b;
  return r;
}
%}

%code requires {
struct V;
}

%union {
  double d;
  V *v;
}

%token <d> NUM
%type <v> expr list

%left '+' '-'
%left '*' '/'
%precedence UMINUS

%%

input : expr                      { result = $1; }
      ;

expr  : NUM                       { $$ = scalar($1); }
      | '[' list ']'              { $$ = $2; $$->vec = true; }
      | expr '+' expr             { $$ = binop('+', $1, $3); }
      | expr '-' expr             { $$ = binop('-', $1, $3); }
      | expr '*' expr             { $$ = binop('*', $1, $3); }
      | expr '/' expr             { $$ = binop('/', $1, $3); }
      | '-' expr %prec UMINUS     { $$ = $2; for (double &d : $$->x) d = -d; }
      | '(' expr ')'              { $$ = $2; }
      ;

list  : expr                      { $$ = $1; }
      | list ',' expr             { $$ = $1; for (double d : $3->x) $$->x.push_back(d); delete $3; }
      ;

%%

void yyerror(const char *msg) {
  std::fprintf(stderr, "error: %s\n", msg);
  failed = true;
}

struct yy_buffer_state;
typedef struct yy_buffer_state *YY_BUFFER_STATE;
YY_BUFFER_STATE yy_scan_string(const char *);

int main(int argc, char **argv) {
  if (argc != 2) {
    std::fprintf(stderr, "usage: ndlang-bison-expr \"<expression>\"\n");
    return 2;
  }
  yy_scan_string(argv[1]);
  if (yyparse() != 0 || failed || !result)
    return 1;
  if (result->vec) {
    std::printf("[");
    for (size_t i = 0; i < result->x.size(); ++i)
      std::printf("%s%f", i ? ", " : "", result->x[i]);
    std::printf("]\n");
  } else {
    std::printf("%f\n", result->x[0]);
  }
  return 0;
}
